CREATE TABLE "GCG_6516_BOM_EXPL" PAGESIZE=4096 (
 "BOM_MASTER" CHAR(50),
 "LEVEL" CHAR(50),
 "PART" CHAR(50),
 "PART_DESC" CHAR(50),
 "UM" CHAR(2),
 "CATEGORY" CHAR(50),
 "SOURCE" CHAR(50),
 "UNIT_COST" DOUBLE,
 "QUANTITY" DOUBLE,
 "INVENTORY_ITEM" CHAR(3),
 "NEXT_PARENT" CHAR(50) );
